# NOTE: WIP
# This file holds parameters that will be used by the pre and post processing
# pipelines. Currently, this file is not used.

# input files holding locations of fasta files and phenotype data
SAMPLES_FILE: data/raw/samples.tsv
PHENOTYPES_FILE: data/raw/phenotypes.tsv

# initial kmer size
K: 30

# in the initial count, any kmers that occur in more than MAX% or fewer than
# MIN% of samples will be dropped.
MAX_KMER_FREQ: 0.98
MIN_KMER_FREQ: 0.02

# proportion of kmers to sample when constructing distance matrix between samples
KMER_SAMPLE_PROP: 0.01

# for each kmer, there must exist a phenotype such that the number of samples
# with data recorded for that phenotype is greater or equal to this threshold
# or that kmer will be thrown out
SAMPLES_THRESH: 5

# the allowed absence/presence ratio for a kmer, phenotype pair. if no phenotypes
# meet this ratio for a kmer, that kmer will be thrown out. For example,
# if there is 1 phenotype of interest, a ratio of 0.05 means for each kmer,
# there must be at least 20 samples that display the phenotype for every sample
# that lacks it.
PHENO_RATIO: 0.05

# maximum number of threads the preprocessing will use concurrently.
MAX_THREADS: 20

# maximum amount of memory in gigabytes (G) the preprocessing/gwas/postprocessing
# will use concurrently.
MAX_MEMORY: 100

